---

spring:
  profiles:
    active: -dev

---

server:
  port: 8001        # 端口号

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client                                # 当前服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql 驱动包
    url: jdbc:mysql://localhost/springcloud01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                               # 数据库连接池的最小维持连接数
      initial-size: 5                                           # 初始化连接数
      max-total: 5                                              # 最大连接数
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

mybatis:
   config-location: classpath:mybatis/mybatis-config.xml        # 加载 mybatis 主配置文件
   type-aliases-package: com.sqp.springcloud.entities           # 指定哪个包下所有类取别名
   mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                         # 加载 mybatis 映射文件

eureka:
  client:
    service-url:
      # Eureka Provider 注册进 Eureka Server（单机）
#      defaultZone: http://localhost:7001/eureka
      # Eureka Provider 注册进 Eureka Server（集群）
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 修改【主机名:服务名】
    instance-id: dept-8001.com
    # 访问路径可以显示IP地址
    prefer-ip-address: true

# 配置Eureka Provider的info信息
info:
  app.name: microservicecloud-config-dept-client
  company.name: www.sqp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 8001        # 端口号

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client                                # 当前服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql 驱动包
    url: jdbc:mysql://localhost/springcloud02?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                               # 数据库连接池的最小维持连接数
      initial-size: 5                                           # 初始化连接数
      max-total: 5                                              # 最大连接数
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

mybatis:
   config-location: classpath:mybatis/mybatis-config.xml        # 加载 mybatis 主配置文件
   type-aliases-package: com.sqp.springcloud.entities           # 指定哪个包下所有类取别名
   mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                         # 加载 mybatis 映射文件

eureka:
  client:
    service-url:
      # Eureka Provider 注册进 Eureka Server（单机）
#      defaultZone: http://localhost:7001/eureka
      # Eureka Provider 注册进 Eureka Server（集群）
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 修改【主机名:服务名】
    instance-id: dept-8001.com
    # 访问路径可以显示IP地址
    prefer-ip-address: true

# 配置Eureka Provider的info信息
info:
  app.name: microservicecloud-config-dept-client
  company.name: www.sqp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$